#!/usr/bin/env ruby
# frozen_string_literal: true

# Advent of Code 2024
#
# Robert Haines
#
# Public Domain

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'aoc2024/extra/cli'

days = AOC2024::Extra::CLI.parse_params(ARGV)

unless days
  warn 'Usage: aoc-2024 <day>'
  exit 1
end

days.each do |day|
  AOC2024::Extra::CLI.run_day(day)
end
